In [23]:
import numpy as np
import pandas as pd

In [24]:
df = pd.read_csv("round1_ijcai_18_train_20180301.txt", sep=' ', encoding='utf-8-sig')

# Question 1

In [25]:
corr_table = df.corr()
corr_table['is_trade'] = corr_table['is_trade'].apply(lambda x: abs(x))
corr_table = corr_table.sort_values(by="is_trade", ascending=False)
corr_table.head()

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,...,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
is_trade,-0.002158,-0.000168,-0.005311,-0.014622,-0.055895,0.037358,0.013972,0.006077,0.000255,0.008843,...,-0.009274,-0.012313,-0.003238,-0.000747,-0.017355,-0.000735,-0.015578,-0.016239,-0.016734,1.000000
item_price_level,-0.000380,0.026952,-0.098667,0.240088,1.000000,-0.029377,0.083133,0.134814,0.001559,0.008266,...,0.023965,0.011926,-0.008429,0.045727,0.341513,0.048414,0.100911,0.099274,0.228606,0.055895
item_sales_level,-0.000263,-0.015316,-0.060640,-0.028618,-0.029377,1.000000,0.853855,0.757697,0.002646,-0.002519,...,0.009675,-0.080792,0.012862,0.463273,0.170366,0.459293,-0.008801,-0.012572,0.097055,0.037358
shop_review_positive_rate,-0.000198,0.002110,-0.095923,0.007857,0.341513,0.170366,0.206513,0.220753,-0.001299,0.000530,...,0.007088,-0.031808,0.029416,0.168541,1.000000,0.166854,0.329895,0.322094,0.465756,0.017355
shop_score_description,-0.000013,-0.000138,-0.060349,-0.004456,0.228606,0.097055,0.126126,0.148225,0.000152,-0.003033,...,0.004154,-0.022656,0.022326,0.070605,0.465756,0.068930,0.938355,0.931128,1.000000,0.016734

# Question 2

In [4]:
df['context_timestamp'] = df['context_timestamp'].apply(lambda x : pd.to_datetime(x, unit='s'))

In [5]:
df1 = df.sort_values(by="context_timestamp", ascending=False)

In [6]:
from datetime import timedelta
date = df1['context_timestamp'].max()
start_date = date - timedelta(2)

In [7]:
tmp = df[df['context_timestamp'] >= start_date].groupby('item_id').count()
tmp['is_trade'].head()

item_id
696490723789804      3
1097631460775571    16
1637165183538885    12
4055398786868336     1
4255654217639344     3
Name: is_trade, dtype: int64

In [8]:
tmp1 = df[df['context_timestamp'] >= start_date].groupby('item_id').sum()
tmp1['is_trade'].head()

item_id
696490723789804     0.0
1097631460775571    1.0
1637165183538885    0.0
4055398786868336    0.0
4255654217639344    0.0
Name: is_trade, dtype: float64

In [9]:
tmp['historical_conversion_rate'] = tmp1['is_trade'] / tmp['is_trade']
tmp['historical_conversion_rate'].head()

item_id
696490723789804     0.0000
1097631460775571    0.0625
1637165183538885    0.0000
4055398786868336    0.0000
4255654217639344    0.0000
Name: historical_conversion_rate, dtype: float64

In [10]:
tmp.reset_index(level=0, inplace=True)
tmp.head()

,item_id,instance_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,historical_conversion_rate
0,696490723789804,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,0.0000
1,1097631460775571,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,0.0625
2,1637165183538885,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,0.0000
3,4055398786868336,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0.0000
4,4255654217639344,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,0.0000

In [11]:
df = pd.merge(df, tmp[['historical_conversion_rate', 'item_id']], on='item_id', how='left')

In [12]:
df.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,historical_conversion_rate
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,0.0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,0.0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,0.0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,0.0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,0.0